### PR TITLE
Update `README.md` with Dracula instructions

### PR DESCRIPTION
**Pull request by ran-dall**
This commits updates the `README.md` doc with the instructions to install the new Dracula theme.

### CODE REVIEW

**Comment by MolassesLover** [comment]
Would you mind getting rid of the broken Discord Shield badge for me as well? Seems better than making another pull request

**Comment by ran-dall** [comment]
discord
discord-canary

These icons? They seem to work for me.

**Comment by MolassesLover** [comment]
I'm referring to the badge at the top of the `README.md` file

**Comment by ran-dall** [comment]
@MolassesLover Lol. I can do that. What is the correct server-id? `953321802124378202` doesn't seem to work.

**Comment by MolassesLover** [comment]
> @MolassesLover Lol. I can do that. What is the correct server-id? `953321802124378202` doesn't seem to work.

That's the thing, the server got deleted so you can just delete the whole badge

**Comment by ran-dall** [comment]
@MolassesLover Done

**Pull request merged**
