### PR TITLE
Add Dracula Theme

### PR DESCRIPTION
**Pull request by ran-dall**
@vinceliuice Lovely theme, mate! I hope you don't mind I started working on a Dracula version. I figured I'd post it here as a draft as I test it and continue to prefect it (so that anyone interested in trying it out, can try it out, and provide me feedback).

Screenshot from 2022-05-02 19-21-00

### CODE REVIEW

**Comment by vinceliuice** [comment]
Looks great!

**Comment by ran-dall** [comment]
@vinceliuice Thank you for merging the theme.

There were a couple of things I was hoping to ask you before we merged it. There are a couple of folders that default to the standard theme. Same with like, for example, Nautilus.

Right now, I was manually correcting them as I found them, but is there a way to integrate this with the theme?

I've attached the custom icons I've made so far.

file-manager
filemanager-actions

**Comment by MolassesLover** [comment]
I think this is a limitation in GNOME; I manually select the right icon by opening the folder details, tapping on the icon, and selecting one from the repository

I hope there is a way to automatically change the folder icons, though, I haven't found a way

**Comment by ran-dall** [comment]
> I think this is a limitation in GNOME; I manually select the right icon by opening the folder details, tapping on the icon, and selecting one from the repository

I don't disagree, however, I think it's more a limitation of our script installing multiple themes. What I've been doing is simply overriding the icons. Like `filemanager-action.svg` does have color themes but none of themes install.

**Comment by MolassesLover** [comment]
You lost me, I don't know what you're referring too, sorry

**Comment by ran-dall** [comment]
@MolassesLover If you do a clean install of the theme (color choice doesn't matter), you'll see that the colorized version of `filemanager-action.svg` doesn't get deployed. It does exist; it just isn't deployed. However, there are some instances where the colorized version was also missing on some of these, but that was an easy fix as just adding the extra icon (like I did with Dracula and the GitHub folder icon) seems to fix it.

**Comment by MolassesLover** [comment]
Oh, that's definitely something on our end that we should fix, nothing to do with GNOME's limitations. That seems worth looking into

**Comment by ran-dall** [comment]
@MolassesLover Yup, it's why I was mentioning it.

**Comment by vinceliuice** [comment]
I'll handle this! this can be fixed by `install.sh`

**Pull request merged**
